//K.importPackage("jit");
//boolean or_1(boolean b1, boolean b2, boolean b3, boolean b4) {
//    return b1 || b2;
//}
//boolean or_2(boolean b1, boolean b2, boolean b3, boolean b4) {
//    return b1 || b2 || b3;
//}
//boolean or_3(boolean b1, boolean b2, boolean b3, boolean b4) {
//    return b1 || (b2 || b3);
//}
//boolean or_4(boolean b1, boolean b2, boolean b3, boolean b4) {
//    return b1 || (b2 || b3) || b4;
//}
//
